name: rv32newlib_msys2

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Run the RISC-V Toolchain build'
        required: true
        default: 'yes'

jobs:
  msys2-ucrt64:
    runs-on: windows-latest
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: UCRT64
          update: true
          install: git mingw-w64-ucrt-x86_64-gcc
      - name: CI-Build
        run: |
          mkdir build
          mkdir /d/opt
          Fsutil.exe file SetCaseSensitiveInfo build
          cd build
          pacman -S --noconfirm mingw-w64-ucrt-x86_64-gcc autoconf automake texinfo curl autotools python mpc-devel gmp-devel gawk bison flex libtool patchutils bc zlib-devel libexpat-devel ninja cmake glib2-devel git gcc
          git clone https://github.com/riscv/riscv-gnu-toolchain
          cd riscv-gnu-toolchain
          sed -i '/shallow = true/d' .gitmodules
          sed -i 's/--depth 1//g' Makefile.in
          CC=x86_64-w64-mingw32-gcc ./configure --prefix=/d/opt/riscv --with-arch=rv32im --with-abi=ilp32 --disable-gdb
          make -j 6
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: riscv-toolchain-rv32-newlib
          path: D:\opt\riscv
